<script lang="ts">
	import { enhance } from '$app/forms';
	import TripCommentForm from '$lib/components/TripCommentForm/TripCommentForm.svelte';
	import TripCommentList from '$lib/components/TripCommentList/TripCommentList.svelte';
	import { writable } from 'svelte/store';
	export let form;
	export let data;

	const comments = writable(data.props.comments);
	$: ({ comments });

</script>

<div class="p-2">
	<div class="grid grid-cols-4 gap-2 items-stretch">
		<div class="col-span-4 h-full">
			<div class="card w-98 bg-base-300 shadow-xl h-full flex flex-col">
				<header class="card-header font-bold flex">
					<a href="/" class="">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							stroke-width="1.5"
							stroke="currentColor"
							class="w-6 h-6 hover:text-green-500"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3"
							/>
						</svg>
					</a>
					<span class="pl-4"></span>
					<h1>Your Trip advice for {data.props.destination}</h1>
				</header>
				<section class="p-4 flex-grow">
					{data.props.advice}
				</section>
				<footer class="card-footer">
					<p class="font-thin text-sm italic">* This trip was generated by GPT</p>
				</footer>
			</div>
		</div>
	</div>
	<div class="grid grid-cols-4 gap-2 items-stretch pt-2">
		<div class="col-span-2 h-full">
			<div class="card w-98 bg-base-300 shadow-xl h-full flex flex-col">
				<header class="card-header font-bold flex">
					<h1>Place new Comment</h1>
				</header>
				<section class="p-4 flex-grow">
					<form use:enhance method="POST" action="?/comment">
						<TripCommentForm />
					</form>
					{#if form?.msg && form?.msg != ""}
						<p>{form.msg}</p>
					{/if}
				</section>
			</div>
		</div>
		<div class="col-span-2 h-full">
			<div class="card w-98 bg-base-300 shadow-xl h-full flex flex-col">
				<header class="card-header font-bold flex">
					<h1>Comments for {data.props.destination}</h1>
				</header>
				<section class="p-4 flex-grow">
					<TripCommentList comments={$comments} />
				</section>
				<footer class="card-footer">
					<p class="font-thin text-sm italic"></p>
				</footer>
			</div>
		</div>
	</div>
</div>
